apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-model-publish-git
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: $(GIT_STORAGE) # replaced by ReplacementTransformer
  storageClassName: $(GIT_STORAGE_CLASS) # replaced by ReplacementTransformer
