
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-model-publish
  name: sas-model-publish

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    sas.com/admin: cluster-wide
  name: sas-model-publish
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - pods/log
  - podtemplates
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - create
  - update
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    sas.com/admin: cluster-local
  name: sas-model-publish
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sas-model-publish
subjects:
- kind: ServiceAccount
  name: sas-model-publish

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-providers: jobExecution-provider,jobExecution-provider-container2
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-model-publish
    sas.com/admin: namespace
    sas.com/registry-sync: default
  name: sas-model-publish
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: sas-model-publish
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/kustomize-base: golang
    sas.com/pod-uses-db-migrator: "true"
    sas.com/pod-uses-liveness-probe: http
    sas.com/pod-uses-readiness-probe: http
    sas.com/pod-uses-startup-probe: http
    sidecar.istio.io/proxyCPU: 15m
    sidecar.istio.io/proxyMemory: 115Mi
  labels:
    app.kubernetes.io/name: sas-model-publish
    sas.com/admin: namespace
    sas.com/deployment-base: golang
    workload.sas.com/class: stateless
  name: sas-model-publish
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-model-publish
  template:
    metadata:
      annotations:
        prometheus.io/path: /internal/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        sas.com/certificate-file-format: pem
        sas.com/kustomize-base: golang
        sas.com/pod-uses-liveness-probe: http
        sas.com/pod-uses-readiness-probe: http
        sas.com/pod-uses-startup-probe: http
        sidecar.istio.io/proxyCPU: 15m
        sidecar.istio.io/proxyMemory: 115Mi
      labels:
        app: sas-model-publish
        app.kubernetes.io/name: sas-model-publish
        workload.sas.com/class: stateless
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - sas-model-publish
              topologyKey: kubernetes.io/hostname
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution: []
      automountServiceAccountToken: true
      containers:
      - env:
        - name: SAS_K8S_DEPLOYMENT_NAME
          value: sas-model-publish
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - secretRef:
            name: sas-consul-client
        - configMapRef:
            name: input
        image: sas-model-publish
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/live
            port: http
            scheme: HTTP
          periodSeconds: 20
          timeoutSeconds: 5
        name: sas-model-publish
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/ready
            port: http
            scheme: HTTP
          periodSeconds: 20
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 180
          httpGet:
            path: /internal/live
            port: http
            scheme: HTTP
          periodSeconds: 10
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      imagePullSecrets: []
      initContainers:
      - args:
        - cp -rf meta /data
        command:
        - /bin/sh
        - -c
        image: sas-model-publish
        imagePullPolicy: IfNotPresent
        name: hydrator
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 75m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: shared-vol
      - env:
        - name: SAS_SERVICE_NAME
          value: sas-model-publish
        - name: SAS_MULTI_TENANCY_REGISTER_SERVICE
          value: "false"
        envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - configMapRef:
            name: sas-java-config
        - secretRef:
            name: sas-consul-client
        image: sas-db-migrator
        imagePullPolicy: IfNotPresent
        name: sas-db-migrator
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 90Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: shared-vol
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: sas-model-publish
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless
      volumes:
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: shared-vol

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    sas.com/ha-class: centralized
    sas.com/kustomize-base: base
  name: sas-model-publish
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-model-publish

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    sas.com/ha-class: centralized
    sas.com/kustomize-base: golang
  name: sas-model-publish
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sas-model-publish
