## Example SecretGenerator to generate the SAS Viya Platform Root CA Certificate secret
##
## In the following code, the locations that require user specified values are indicated by a capitalized and
## hyphenated name set off by curly braces and a space at each end. You should replace this token with the
## actual value.
## Replace the curly braces, interior spaces, and the variable name.
## For instance, "{{ SAS_VIYA_CA_CERTIFICATE_FILE_NAME }}"
## should be replaced by the path to a .pem file containing your SAS Viya Platform Root CA Certificate.
## If you use the suggested example directory structure, the correct, final syntax would resemble the following:
## - tls.crt=site-config/security/sas-viya-ca-certificate.pem
## - tls.key=site-config/security/sas-viya-ca-certificate.key
## - ca.crt=site-config/security/sas-viya-ca-certificate-ca-chain.pem
##
##  Special Note:  the name of the Kubernetes secret which will contain the certificate and key can be
##  renamed.  However, the name provided below "sas-viya-ca-certificate-secret" is referenced in other kustomization
##  files.  If you change the name below, you will need to change all the other references: All the objects' spec.tls.secretName
##  and the "sas-certframe-user-config" config map's SAS_CA_CERTIFICATE_SECRET_NAME environment variable.
---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: sas-viya-ca-certificate-secret
options:
  disableNameSuffixHash: true
## This file specifies the SAS Viya Platform Root CA certificate and key.
## The files named below must exist in a directory under your kustomization.yaml prior to running the 'kustomize build'
## command, and they must be readable by the user ID that is running the kustomize command.
## The tls.crt and ca.crt certificate files contain the CA certificate chain used to sign internal SAS Viya Platform
## server certificates. Certificates are ordered according to issuer hierarchy. The hierarchy starts with the intermediate
## CA certificate which will sign SAS Viya Platform server certificates, followed by its issuer, then followed by its issuer
## and so on, up to and including the root CA certificate. SAS recommends including the root CA certificate as the last certificate
## in the tls.crt file. While not strictly required, this makes it more convenient for clients to obtain the root CA certificate.
## SAS recommends using the same file for ca.crt as you used for tls.crt.
## The certificates and key will be copied into the Kubernetes secret named above. The files can be deleted after you run the
## 'kustomize build' command with the modified kustomization files in place.
files:
  - tls.crt={{ SAS_VIYA_CA_CERTIFICATE_FILE_NAME }} # For example: site-config/security/sas-viya-ca-certificate.pem
  - tls.key={{ SAS_VIYA_CA_CERTIFICATE_KEY_FILE_NAME }} # For example: site-config/security/sas-viya-ca-certificate-key.pem
  - ca.crt={{  SAS_VIYA_CA_CERTIFICATE_FILE_NAME }} # For example: site-config/security/sas-viya-ca-certificate.pem
type: "kubernetes.io/tls"
