apiVersion: builtin
kind: PatchTransformer
metadata:
  name: large-model-resource-transformer
patch: |-
  # Increase resource requests and limits for sas-files service
  - op: replace
    path: /spec/template/spec/containers/0/resources/requests/cpu
    value: 2
  - op: replace
    path: /spec/template/spec/containers/0/resources/requests/memory
    value: 4Gi
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/cpu
    value: 2
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/memory
    value: 4Gi
target:
  kind: Deployment
  name: sas-files
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: large-model-launcher-resource-transformer
patch: |-
  # Increase resource requests and limits for sas-launcher service
  - op: replace
    path: /spec/template/spec/containers/0/resources/requests/cpu
    value: 4
  - op: replace
    path: /spec/template/spec/containers/0/resources/requests/memory
    value: 8Gi
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/cpu
    value: 4
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/memory
    value: 8Gi
target:
  kind: Deployment
  name: sas-launcher
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: large-model-repository-resource-transformer
patch: |-
  # Increase resource requests and limits for sas-model-repository service
  - op: replace
    path: /spec/template/spec/containers/0/resources/requests/cpu
    value: 2
  - op: replace
    path: /spec/template/spec/containers/0/resources/requests/memory
    value: 4Gi
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/cpu
    value: 2
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/memory
    value: 4Gi
target:
  kind: Deployment
  name: sas-model-manager
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: large-model-catalog-resource-transformer
patch: |-
  # Increase resource requests and limits for sas-catalog-services
  - op: replace
    path: /spec/template/spec/containers/0/resources/requests/cpu
    value: 2
  - op: replace
    path: /spec/template/spec/containers/0/resources/requests/memory
    value: 4Gi
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/cpu
    value: 2
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/memory
    value: 4Gi
target:
  kind: Deployment
  name: sas-catalog-services
