---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgo
  labels:
    sas.com/zero-scale-phase: "1"
  annotations: {}
spec:
  replicas: 1
  strategy: { type: Recreate }
  template:
    metadata:
      annotations:
        sas.com/certificate-file-format: pem
    spec:
      serviceAccountName: pgo
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets: []
      initContainers: []
      volumes: []
      containers:
      - name: operator
        image: sas-crunchy5-postgres-operator
        env:
        - name: PGO_INSTALLER
          value: kustomize
        - name: PGO_INSTALLER_ORIGIN
          value: customer-portal
        - name: PGO_CONTROLLER_LEASE_NAME
          value: cpk-leader-election-lease
        - name: PGO_NAMESPACE
          valueFrom: { fieldRef: { fieldPath: metadata.namespace } }
        - name: CRUNCHY_DEBUG
          value: "false"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities: { drop: [ALL] }
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        livenessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
          - weight: 50
            preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless