---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-consul-remove-duplicate-volume-full-stack-tls-transformer
patch: |-
  - op: remove
    path: /spec/template/spec/volumes/3
  - op: remove
    path: /spec/template/spec/volumes/2
target:
  kind: StatefulSet
  name: sas-consul-server
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-base-statefulset-sas-consul-server-full-stack-tls-transformer
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0
    value:
      name: sas-certframe
      image: sas-certframe
      env:
      - name: KUBE_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: SAS_CERTFRAME_TOKEN_DIR
        value: /certframe-token
      - name: SAS_ADDITIONAL_CA_CERTIFICATES_DIR
        value: /customer-provided-ca-certificates
      envFrom:
      - configMapRef:
          name: sas-certframe-config
      - configMapRef:
          name: sas-certframe-ingress-certificate-config
      - configMapRef:
          name: sas-certframe-user-config
      volumeMounts:
      - name: certframe-token
        mountPath: /certframe-token
      - name: security
        mountPath: /security
      - name: customer-provided-ca-certificates
        mountPath: /customer-provided-ca-certificates
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "500Mi"
          cpu: "500m"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: certframe-token
      secret:
        secretName: sas-certframe-token
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: security
      emptyDir: {}
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: customer-provided-ca-certificates
      configMap:
        name: sas-customer-provided-ca-certificates
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /security
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts
      subPath: cacerts
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /opt/sas/viya/config/etc/SASSecurityCertificateFramework/private
      subPath: private
  - op: add
    path: /spec/template/metadata/annotations/sas.com~1tls-enabled-ports
    value: all
  - op: replace
    path: /spec/template/metadata/annotations/prometheus.io~1scheme
    value: https
  - op: add
    path: /spec/template/metadata/annotations/sas.com~1tls-mode
    value: full-stack
  - op: add
    path: /metadata/annotations/sas.com~1tls-mode
    value: full-stack
  - op: add
    path: /spec/template/spec/containers/0/envFrom/0
    value:
      configMapRef:
        name: sas-tls-config
target:
  kind: StatefulSet
  name: sas-consul-server
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-consul-http-addr-go-config-full-stack-tls-transformer
patch: |-
  - op: replace
    path: /data/CONSUL_HTTP_ADDR
    value: https://sas-consul-server:8500
target:
  kind: ConfigMap
  name: sas-go-config
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-consul-http-addr-java-config-full-stack-tls-transformer
patch: |-
  - op: replace
    path: /data/CONSUL_HTTP_ADDR
    value: https://sas-consul-server:8500
  - op: replace
    path: /data/JAVA_GLOBAL_OPTION_CONSUL_SCHEME
    value: -Dspring.cloud.consul.scheme=https
target:
  kind: ConfigMap
  name: sas-java-config
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-consul-http-addr-postgres-config-full-stack-tls-transformer
patch: |-
  - op: add
    path: /data/CONSUL_HTTP_ADDR
    value: https://sas-consul-server:8500
target:
  kind: ConfigMap
  name: sas-postgres-config
