---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cpk
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - security.crunchydata.com
  resources:
  - postgresstigassessments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.crunchydata.com
  resources:
  - postgresstigassessments/finalizers
  verbs:
  - update
- apiGroups:
  - security.crunchydata.com
  resources:
  - postgresstigassessments/status
  verbs:
  - get
  - patch
  - update
