---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-model-management
    sas.com/admin: namespace
  name: sas-model-management
spec:
  routes:
  - conditions:
    - prefix: /modelManagement
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /modelManagement/
    services:
    - name: sas-model-management
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /modelManagement/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-model-management
      port: 80
    timeoutPolicy:
      response: 300s

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-model-repository
    sas.com/admin: namespace
  name: sas-model-repository
spec:
  routes:
  - conditions:
    - prefix: /modelRepository
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /modelRepository/
    services:
    - name: sas-model-repository
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /modelRepository/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-model-repository
      port: 80
    timeoutPolicy:
      response: 300s

