apiVersion: v1
kind: PodTemplate
metadata:
  name: sas-decisions-runtime-builder-buildkit-job-config
template:
  metadata:
    annotations:
      sidecar.istio.io/inject: "false"
    labels:
      sas.com/deployment: sas-viya
      workload.sas.com/class: stateless
  spec:
    securityContext:
      # fsGroup: {{ FSGROUP_VALUE }}  # required for openshift only
      runAsNonRoot: true
    tolerations:
      - key: workload.sas.com/class
        operator: Equal
        value: stateful
        effect: NoSchedule
      - key: workload.sas.com/class
        operator: Equal
        value: stateless
        effect: NoSchedule
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: workload.sas.com/class
                  operator: In
                  values:
                    - stateless
          - weight: 50
            preference:
              matchExpressions:
                - key: workload.sas.com/class
                  operator: NotIn
                  values:
                    - compute
                    - cas
                    - stateful
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.azure.com/mode
                  operator: NotIn
                  values:
                    - system
    restartPolicy: Never
    schedulerName: default-scheduler
    serviceAccount: sas-decisions-runtime-builder-buildkit
    serviceAccountName: sas-decisions-runtime-builder-buildkit
    terminationGracePeriodSeconds: 30
    dnsPolicy: ClusterFirst
    imagePullSecrets:
      - name: sas-image-pull-secrets
    volumes:
      - emptyDir: {}
        name: workspace
      - name: buildkit
        persistentVolumeClaim:
          claimName: sas-decisions-runtime-builder-buildkit
      - name: certs
        secret:
          defaultMode: 420
          secretName: buildkit-client-certs
    containers:
      - args:
          - --addr
          - tcp://buildkitd:1234
          - --tlscacert
          - /certs/ca.pem
          - --tlscert
          - /certs/cert.pem
          - --tlskey
          - /certs/key.pem
          - build
          - --frontend
          - dockerfile.v0
          - --local
          - context=/workspace
          - --local
          - dockerfile=/workspace
          - --output
        command:
          - buildctl
        env:
          - name: BUILDKITD_FLAGS
            value: --oci-worker-no-process-sandbox
          - name: DOCKER_CONFIG
            value: /kaniko/.docker
          - name: XDG_CACHE_HOME
            value: /cache/.cache

        image: sas-buildkit
        imagePullPolicy: IfNotPresent
        name: buildkit
        resources: {}
        securityContext:
          procMount: Default
          runAsGroup: 1001
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /workspace
            name: workspace
          - mountPath: /certs
            name: certs
          - mountPath: /cache
            name: buildkit
    initContainers:
      - command:
          - /bin/sh
          - -c
          - cp -rf /manifest /workspace && mkdir /workspace/unzipped && cp -rf /modules/* /workspace/unzipped
        image: scr
        imagePullPolicy: Always
        name: buildkit-prep
        resources: {}
        securityContext:
          runAsGroup: 1001
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /workspace
            name: workspace
      - command:
          - /bin/sh
          - -c
        env:
          - name: SAS_CONTAINER_RUNTIME_IMAGE
            valueFrom:
              configMapKeyRef:
                key: SAS_COMPONENT_RELPATH_sas-decisions-runtime-base
                name: sas-components
          - name: SAS_CONTAINER_RUNTIME_IMAGE_TAG
            valueFrom:
              configMapKeyRef:
                key: SAS_COMPONENT_TAG_sas-decisions-runtime-base
                name: sas-components
          - name: SAS_CONTAINER_RUNTIME_COMPONENTS_IMAGE
            valueFrom:
              configMapKeyRef:
                key: SAS_COMPONENT_RELPATH_sas-decisions-runtime-components
                name: sas-components
          - name: SAS_CONTAINER_RUNTIME_COMPONENTS_IMAGE_TAG
            valueFrom:
              configMapKeyRef:
                key: SAS_COMPONENT_TAG_sas-decisions-runtime-components
                name: sas-components
        envFrom:
          - configMapRef:
              name: input
        image: sas-decisions-runtime-builder
        imagePullPolicy: IfNotPresent
        name: dockergen
        resources: {}
        securityContext:
          runAsGroup: 1001
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /workspace
            name: workspace
