---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: compute-server-add-nfs-mount
patch: |-
  - op: add
    path: /template/spec/volumes/-
    value:
      name: nfs-data
      nfs:
        path: /scotia-peru-export/viya/data
        server: 192.168.3.4
  - op: add
    path: /template/spec/containers/0/volumeMounts/-
    value:
      mountPath: /mnt/viya-share/data
      name: nfs-data
target:
  kind: PodTemplate
  version: v1
  labelSelector: sas.com/template-intent=sas-launcher
