
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-14cc4e04ccfe16aa
patch: |-
  - op: add
    path: /spec/selector/matchExpressions
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-7f26f2f24bd3021f
patch: |-
  - op: add
    path: /spec/template/spec/initContainers
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-625179392bfb55ae
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/command
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-0082f8aab729621e
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/args
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-c9413e23f62c0f53
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/resizePolicy
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-42021d668daff02a
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/volumeDevices
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-f152109b98bb98ac
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/livenessProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-caae2ee8917ef741
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/readinessProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-d0fe25993af15d50
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/startupProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-6130bc2a0ccc0b75
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/securityContext/capabilities/add
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-bf5ce12c3374b5a4
patch: |-
  - op: add
    path: /spec/template/spec/ephemeralContainers
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-6bdcfbc446d67c5d
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/supplementalGroups
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-58c27ca671d948ca
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/sysctls
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-4a102b52750f9ca4
patch: |-
  - op: add
    path: /spec/template/spec/imagePullSecrets
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-61a5499626b2b19d
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-2f0f65e238f22d88
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/preference/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-7c6be52009e03d7f
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/1/preference/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-37ef32dc299a2825
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-23b38f8ed29e0b21
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/namespaces
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-30c75ea6d9b5550a
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/matchLabelKeys
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-307348a99d20b687
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/mismatchLabelKeys
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-06b72bb3d36fb287
patch: |-
  - op: add
    path: /spec/template/spec/hostAliases
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-532dea9f74d1d675
patch: |-
  - op: add
    path: /spec/template/spec/readinessGates
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-7d4bb05d1488631f
patch: |-
  - op: add
    path: /spec/template/spec/topologySpreadConstraints
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-0ffebc93d46b2e47
patch: |-
  - op: add
    path: /spec/template/spec/schedulingGates
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-eb5d5f3ca813f07a
patch: |-
  - op: add
    path: /spec/template/spec/resourceClaims
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
