
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-launcher
  name: sas-launcher

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    sas.com/admin: cluster-wide
  name: sas-launcher
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - patch
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - podtemplates
  - events
  - persistentvolumeclaims
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  - pods
  - persistentvolumeclaims
  verbs:
  - watch
- apiGroups:
  - ""
  resources:
  - pods/resize
  verbs:
  - patch
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  - jobs/finalizers
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
  - list
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    sas.com/admin: cluster-local
  name: sas-launcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sas-launcher
subjects:
- kind: ServiceAccount
  name: sas-launcher

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-launcher
    sas.com/admin: namespace
    sas.com/registry-sync: default
  name: sas-launcher
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: sas-launcher
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sas.com/certificate-file-format: jks
    sas.com/kustomize-base: spring
    sas.com/pod-uses-liveness-probe: http
    sas.com/pod-uses-readiness-probe: http
    sas.com/pod-uses-startup-probe: http
    sidecar.istio.io/proxyCPU: 15m
    sidecar.istio.io/proxyMemory: 115Mi
  labels:
    app.kubernetes.io/name: sas-launcher
    sas.com/admin: namespace
    sas.com/deployment-base: spring
    workload.sas.com/class: stateless
  name: sas-launcher
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-launcher
  template:
    metadata:
      annotations:
        prometheus.io/path: /internal/metrics
        prometheus.io/port: "10445"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        sas.com/certificate-file-format: jks
        sas.com/kustomize-base: spring
        sas.com/pod-uses-liveness-probe: http
        sas.com/pod-uses-readiness-probe: http
        sas.com/pod-uses-startup-probe: http
        sidecar.istio.io/proxyCPU: 15m
        sidecar.istio.io/proxyMemory: 115Mi
      labels:
        app: sas-launcher
        app.kubernetes.io/name: sas-launcher
        workload.sas.com/class: stateless
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - sas-launcher
              topologyKey: kubernetes.io/hostname
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution: []
      automountServiceAccountToken: true
      containers:
      - env:
        - name: SAS_K8S_DEPLOYMENT_NAME
          value: sas-launcher
        - name: SAS_LAUNCHER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SAS_LAUNCHER_USER_PROCESS_LIMIT
          value: "10"
        - name: SAS_LAUNCHER_USER_PROCESS_LIMIT_ENABLED
          value: "true"
        - name: SAS_LAUNCHER_SUPER_USER_PROCESS_LIMIT
          value: "15"
        - name: SAS_LAUNCHER_SUPER_USER_PROCESS_LIMIT_ENABLED
          value: "true"
        - name: SAS_LAUNCHER_SWO_DISABLED
          value: "false"
        - name: SAS_EVENT_CONFIGURATION_ARKE_ENABLED
          value: "true"
        - name: JAVA_OPTION_XSS
          value: -Xss320k
        envFrom:
        - configMapRef:
            name: sas-java-config
        - configMapRef:
            name: sas-shared-config
        - secretRef:
            name: sas-consul-client
        - configMapRef:
            name: sas-spring-23-management-config
        - configMapRef:
            name: sas-launcher-init-nls-config
        image: sas-launcher
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/live
            port: http-internal
            scheme: HTTP
          periodSeconds: 20
          timeoutSeconds: 5
        name: sas-launcher
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 10445
          name: http-internal
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/ready
            port: http-internal
            scheme: HTTP
          periodSeconds: 20
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 1024Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 360
          httpGet:
            path: /internal/live
            port: http-internal
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /opt/sas/viya/config/tmp
          name: tmp
      imagePullSecrets: []
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: sas-launcher
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless
      volumes:
      - emptyDir: {}
        name: tmp

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    sas.com/ha-class: centralized
    sas.com/kustomize-base: base
  name: sas-launcher
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-launcher

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    sas.com/ha-class: decentralized
    sas.com/kustomize-base: decentralized
  name: sas-launcher-job
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      launcher.sas.com/job-type: sas-launcher-job

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    sas.com/ha-class: centralized
    sas.com/kustomize-base: spring
  name: sas-launcher
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sas-launcher

---
apiVersion: v1
kind: PodTemplate
metadata:
  annotations:
    launcher.sas.com/jobContainerName: sas-programming-environment
    sas.com/certificate-file-format: pem
    sas.com/config-init-mode: initcontainer
    sas.com/kustomize-base: sas-programming-environment
    sas.com/sas-access-config: "true"
    sas.com/sas-kerberos-config: "true"
    sas.com/sas-sssd-config: "true"
    sas.com/tenant-resource: "true"
  labels:
    sas.com/admin: namespace
    sas.com/pod-container-image: sas-programming-environment
    sas.com/template-intent: sas-launcher
    workload.sas.com/class: compute
  name: sas-launcher-job-config
template:
  metadata:
    annotations:
      sas.com/certificate-file-format: pem
      sas.com/kustomize-base: sas-programming-environment
      sidecar.istio.io/inject: "false"
    labels:
      launcher.sas.com/job-type: sas-launcher-job
  spec:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: In
              values:
              - compute
          weight: 100
        - preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: NotIn
              values:
              - cas
              - stateless
              - stateful
          weight: 50
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.azure.com/mode
              operator: NotIn
              values:
              - system
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []
        requiredDuringSchedulingIgnoredDuringExecution: []
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []
        requiredDuringSchedulingIgnoredDuringExecution: []
    automountServiceAccountToken: true
    containers:
    - env:
      - name: SAS_K8S_POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: SAS_K8S_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: SAS_LICENSE
        valueFrom:
          secretKeyRef:
            key: SAS_LICENSE
            name: sas-license
      - name: SASCLOUDNATIVE
        value: "1"
      - name: LAUNCH_AS_JOB
        value: "true"
      envFrom:
      - configMapRef:
          name: sas-access-config
      - configMapRef:
          name: sas-deployment-metadata
      - configMapRef:
          name: sas-launcher-lockdown-config
      - configMapRef:
          name: sas-programming-environment-path-config
      - configMapRef:
          name: sas-shared-config
      image: sas-programming-environment
      name: sas-programming-environment
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
      volumeMounts:
      - mountPath: /tmp
        name: tmp
      - mountPath: /sasuser
        name: sasuser
      - mountPath: /sashelp
        name: sashelp
      - mountPath: /config
        name: config
      - mountPath: /opt/sas/viya/config/var
        name: viya
      - mountPath: /opt/sas/viya/home/commonfiles
        name: commonfilesvols
        readOnly: true
    imagePullSecrets: []
    initContainers:
    - env:
      - name: SAS_K8S_POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: SAS_K8S_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      envFrom:
      - configMapRef:
          name: sas-go-config
      - configMapRef:
          name: sas-shared-config
      - secretRef:
          name: sas-consul-client
      - configMapRef:
          name: sas-programming-environment-path-config
      - configMapRef:
          name: sas-deployment-metadata
      - configMapRef:
          name: sas-programming-environment-java-policy-config
      - configMapRef:
          name: sas-access-config
      image: sas-config-init
      name: sas-config-init
      resources:
        limits:
          cpu: 2
          memory: 500Mi
        requests:
          cpu: 50m
          memory: 50Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 1001
        runAsUser: 1001
      volumeMounts:
      - mountPath: /tmp
        name: config-init-tmp
      - mountPath: /config
        name: config
      - mountPath: /opt/sas/viya/config/var
        name: viya
      - mountPath: /opt/sas/viya/home/commonfiles
        name: commonfilesvols
        readOnly: true
    restartPolicy: Never
    securityContext:
      fsGroupChangePolicy: OnRootMismatch
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    serviceAccountName: sas-programming-environment
    tolerations:
    - effect: NoSchedule
      key: workload.sas.com/class
      operator: Equal
      value: compute
    volumes:
    - emptyDir: {}
      name: tmp
    - emptyDir: {}
      name: config-init-tmp
    - emptyDir: {}
      name: sasuser
    - emptyDir: {}
      name: sashelp
    - emptyDir: {}
      name: config
    - emptyDir: {}
      name: viya
    - name: commonfilesvols
      persistentVolumeClaim:
        claimName: sas-commonfiles
        readOnly: true
