
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-961295148ba9fb91
patch: |-
  - op: add
    path: /spec/selector/matchExpressions
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-299cad91fec87686
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/ports
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-289965d96c45da31
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/envFrom
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-d2c1536479a475f5
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/env
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-87647e2ba0444174
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/resizePolicy
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-18635023bbe905e7
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/volumeDevices
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-6baddcc5aaa30f96
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/securityContext/capabilities/add
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-ec6ae0b95a4d7c18
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/command
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-1081cdf97f00f896
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/args
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-83c1cd85165ed169
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/ports
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-c9e80d80ebc91b75
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/resizePolicy
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-8891987078a5af48
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/volumeDevices
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-1d051a0d79bb6513
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/securityContext/capabilities/add
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-ad1c8d26a8b06e8d
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/command
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-83e2838af4d7c15d
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/args
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-f30950510fc9bf12
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/resizePolicy
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-c123052e0cba0c11
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/volumeDevices
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-d2fc1a2de5d78fd3
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/livenessProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-df1d2d2cd2cfe228
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/readinessProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-f2dc8c912d230f3f
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/startupProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-7342a97f983a6714
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/securityContext/capabilities/add
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-73f91a2476a749e3
patch: |-
  - op: add
    path: /spec/template/spec/containers/1/ports
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-25ecdc37fcf055a3
patch: |-
  - op: add
    path: /spec/template/spec/containers/1/resizePolicy
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-b533078799a4cdea
patch: |-
  - op: add
    path: /spec/template/spec/containers/1/volumeDevices
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-48ea5dc1a4bd80e9
patch: |-
  - op: add
    path: /spec/template/spec/containers/1/securityContext/capabilities/add
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-ea15608b3df5267b
patch: |-
  - op: add
    path: /spec/template/spec/ephemeralContainers
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-c707f37d188aa6ac
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/supplementalGroups
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-7b99b28260c43ab1
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/sysctls
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-a510ccd9d3f6c37b
patch: |-
  - op: add
    path: /spec/template/spec/imagePullSecrets
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-215ceef3dfe0f3ec
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-ebb7449e02120367
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/preference/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-f71cd1e23db64606
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/1/preference/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-9e9a90bd932702a4
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-ed762c9965613f88
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/namespaces
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-3883158e547824f1
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/matchLabelKeys
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-81f29d8ae5f7e6de
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/mismatchLabelKeys
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-cc85d0a9da417ade
patch: |-
  - op: add
    path: /spec/template/spec/hostAliases
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-794cb745a6b51014
patch: |-
  - op: add
    path: /spec/template/spec/readinessGates
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-3c57fc2ebc3883a6
patch: |-
  - op: add
    path: /spec/template/spec/topologySpreadConstraints
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-a4ba70178323f99e
patch: |-
  - op: add
    path: /spec/template/spec/schedulingGates
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-0ec84dbc65b51fc1
patch: |-
  - op: add
    path: /spec/template/spec/resourceClaims
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-cirrus-core
  version: v1
