
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-risk-cirrus-core
  name: sas-risk-cirrus-core

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sas-risk-cirrus-core
rules:
- apiGroups:
  - ""
  resources:
  - podtemplates
  - pods
  - pods/log
  - configmaps
  verbs:
  - get
  - patch
  - list
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sas-risk-cirrus-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sas-risk-cirrus-core
subjects:
- kind: ServiceAccount
  name: sas-risk-cirrus-core

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-risk-cirrus-core
    sas.com/admin: namespace
    sas.com/registry-sync: default
  name: sas-risk-cirrus-core
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: sas-risk-cirrus-core
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    sas.com/backup-role: provider
  name: sas-risk-cirrus-core
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    sas.com/backup-role: storage
  name: sas-risk-cirrus-core-backup-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 16Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/kustomize-base: golang
    sas.com/pod-uses-db-migrator: "true"
    sas.com/pod-uses-liveness-probe: http
    sas.com/pod-uses-readiness-probe: http
    sas.com/pod-uses-startup-probe: http
    sidecar.istio.io/proxyCPU: 15m
    sidecar.istio.io/proxyMemory: 115Mi
  labels:
    app.kubernetes.io/name: sas-risk-cirrus-core
    sas.com/admin: namespace
    sas.com/backup-role: provider
    sas.com/deployment-base: golang
    sas.com/sas-backup-datasource-types: fileSystem
    workload.sas.com/class: stateless
  name: sas-risk-cirrus-core
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-risk-cirrus-core
  template:
    metadata:
      annotations:
        prometheus.io/path: /internal/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        sas.com/certificate-file-format: pem
        sas.com/kustomize-base: golang
        sas.com/pod-uses-liveness-probe: http
        sas.com/pod-uses-readiness-probe: http
        sas.com/pod-uses-startup-probe: http
        sidecar.istio.io/proxyCPU: 15m
        sidecar.istio.io/proxyMemory: 115Mi
      labels:
        app: sas-risk-cirrus-core
        app.kubernetes.io/name: sas-risk-cirrus-core
        workload.sas.com/class: stateless
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - sas-risk-cirrus-core
              topologyKey: kubernetes.io/hostname
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution: []
      automountServiceAccountToken: true
      containers:
      - env:
        - name: SAS_K8S_DEPLOYMENT_NAME
          value: sas-risk-cirrus-core
        envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - secretRef:
            name: sas-consul-client
        - configMapRef:
            name: sas-risk-cirrus-core-service-parameters
        - configMapRef:
            name: sas-restore-job-parameters
        image: sas-risk-cirrus-core
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/live
            port: http
            scheme: HTTP
          periodSeconds: 20
          timeoutSeconds: 5
        name: sas-risk-cirrus-core
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/ready
            port: http
            scheme: HTTP
          periodSeconds: 20
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 2000Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 180
          httpGet:
            path: /internal/live
            port: http
            scheme: HTTP
          periodSeconds: 10
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /riskcirruscore
          name: sas-risk-cirrus-core
        - mountPath: /sasviyabackup
          name: sas-risk-cirrus-core-backup-data
      - args:
        - -c
        - while true; do /opt/sas/viya/home/bin/backup_agent_job_start.sh; echo 'restarting
          backup script'; sleep 10; done & wait;
        command:
        - /bin/bash
        env:
        - name: BACKUP_MOUNT_LOCATION
          value: /sasviyabackup
        - name: BACKUP_SOURCE_MOUNTS
          value: sas-risk-cirrus-core
        - name: sas-risk-cirrus-core
          value: /riskcirruscore
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - configMapRef:
            name: sas-java-config
        - configMapRef:
            name: sas-backup-agent-parameters
        - secretRef:
            name: sas-consul-client
        image: sas-backup-agent
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - bash
              - -c
              - pkill -SIGKILL 'backup-agent' ; kill -SIGKILL $(ps -Af | grep 'backup_agent_job_start.sh'  |
                grep -v grep | awk '{print $2}')
        name: sas-backup-agent
        resources:
          limits:
            cpu: 100m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sasviyabackup
          name: sas-risk-cirrus-core-backup-data
        - mountPath: /riskcirruscore
          name: sas-risk-cirrus-core
      imagePullSecrets: []
      initContainers:
      - args:
        - cp -rf meta /data
        command:
        - /bin/sh
        - -c
        image: sas-risk-cirrus-core
        imagePullPolicy: IfNotPresent
        name: hydrator
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 75m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: shared-vol
      - env:
        - name: SAS_SERVICE_NAME
          value: sas-risk-cirrus-core
        - name: SAS_MULTI_TENANCY_REGISTER_SERVICE
          value: "false"
        envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - configMapRef:
            name: sas-java-config
        - secretRef:
            name: sas-consul-client
        image: sas-db-migrator
        imagePullPolicy: IfNotPresent
        name: sas-db-migrator
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 90Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: shared-vol
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: sas-risk-cirrus-core
      serviceAccountName: sas-risk-cirrus-core
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless
      volumes:
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: shared-vol
      - name: sas-risk-cirrus-core-backup-data
        persistentVolumeClaim:
          claimName: sas-risk-cirrus-core-backup-data
      - name: sas-risk-cirrus-core
        persistentVolumeClaim:
          claimName: sas-risk-cirrus-core

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    sas.com/ha-class: centralized
    sas.com/kustomize-base: golang
  name: sas-risk-cirrus-core
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sas-risk-cirrus-core
