
---
apiVersion: v1
kind: PodTemplate
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/kustomize-base: base
  labels:
    sas.com/admin: namespace
    workload.sas.com/class: stateless
  name: sas-model-builder-job
template:
  metadata:
    annotations:
      sas.com/certificate-file-format: pem
      sas.com/kustomize-base: base
    labels:
      workload.sas.com/class: stateless
  spec:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: In
              values:
              - stateless
          weight: 100
        - preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: NotIn
              values:
              - cas
              - compute
              - stateful
          weight: 50
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.azure.com/mode
              operator: NotIn
              values:
              - system
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []
        requiredDuringSchedulingIgnoredDuringExecution: []
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []
        requiredDuringSchedulingIgnoredDuringExecution: []
    automountServiceAccountToken: false
    containers:
    - env: []
      envFrom:
      - configMapRef:
          name: sas-shared-config
      image: sas-model-builder-job
      name: sas-model-builder-job
      resources:
        requests:
          cpu: "2"
          memory: 1.5Gi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
      volumeMounts:
      - mountPath: /tmp
        name: tmp
    imagePullSecrets: []
    initContainers: []
    restartPolicy: Never
    securityContext:
      runAsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001
      seccompProfile:
        type: RuntimeDefault
    serviceAccount: sas-programming-environment
    serviceAccountName: sas-programming-environment
    tolerations:
    - effect: NoSchedule
      key: workload.sas.com/class
      operator: Equal
      value: stateless
    - effect: NoSchedule
      key: workload.sas.com/class
      operator: Equal
      value: stateful
    volumes:
    - emptyDir: {}
      name: tmp
