apiVersion: orchestration.sas.com/v2beta10
kind: LifecycleOperation
metadata:
  annotations:
    lifecycle.orchestration.sas.com/publish: "true"
    sas.com/component-name: sas-k8s-common
    sas.com/component-version: 2.108.0-20250904.1756998319075
  creationTimestamp: null
  name: assess
spec:
  args:
  - name: namespace
  - name: manifest
  - default: 7200s
    name: timeout
  steps:
  - always: true
    args:
    - $operation
    - --namespace
    - $namespace
    - --timeout
    - $timeout
    - --manifest
    - $manifest
    cmd: run
    withOperations:
      labelSelector: participate.lifecycle.sas.com/assess=true
