apiVersion: orchestration.sas.com/v2beta4
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-commonfiles
    sas.com/component-version: 2.17.23-20250909.1757415529480
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: sas-commonfiles
  name: deploy-assess-commonfiles
spec:
  args:
  - name: namespace
  - name: manifest
  steps:
  - args:
    - deploy-assess-commonfiles-execute
    - --namespace
    - $namespace
    cmd: run
    when: |-
      (or
        (.ManifestResource $manifest (((((.NewManifestResourcesIterationSpec).WithGroup "batch").WithVersion "v1").WithKind "Job").WithName "sas-commonfiles"))
        (.ClusterResource ((((((.NewClusterResourcesIterationSpec).WithNamespace $namespace).WithGroup "batch").WithVersion "v1").WithResource "job").WithName "sas-commonfiles"))
      )
