apiVersion: orchestration.sas.com/v2beta10
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-k8s-common
    sas.com/component-version: 2.108.0-20250904.1756998319075
  creationTimestamp: null
  labels:
    participate.lifecycle.sas.com/deploy-post: "true"
  name: deploy-post-openshift
spec:
  args:
  - name: namespace
    required: true
  steps:
  - always: true
    args:
    - delete
    - --namespace
    - $namespace
    - --ignore-not-found
    - rolebinding
    - sas-predeploy-openshift-route
    cmd: kubectl
    when: (.GetVariable "sas.com/route-permissions")
  - always: true
    args:
    - delete
    - --namespace
    - $namespace
    - --ignore-not-found
    - role
    - sas-predeploy-openshift-route
    cmd: kubectl
    when: (.GetVariable "sas.com/route-permissions")
