apiVersion: orchestration.sas.com/v2beta10
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-k8s-common
    sas.com/component-version: 2.108.0-20250904.1756998319075
  creationTimestamp: null
  name: scale-up
spec:
  args:
  - name: namespace
  - default: 7200s
    name: timeout
  steps:
  - args:
    - 'DEPRECATED: Replaced by start-all'
    cmd: log
  - args:
    - start-all
    - --namespace
    - $namespace
    - --timeout
    - $timeout
    cmd: run
