apiVersion: orchestration.sas.com/v2beta15
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-cas-operator
    sas.com/component-version: 3.59.10-20250902.1756846578310
  creationTimestamp: null
  labels:
    participate.lifecycle.sas.com/start-all-execute-phase-0: "true"
  name: start-all-execute-cas
spec:
  args:
  - name: namespace
  steps:
  - args:
    - patch
    - --namespace
    - $namespace
    - casdeployments
    - $resource.Name
    - --type
    - json
    - --patch
    - '(print "[{\"op\":\"replace\", \"path\": \"/spec/shutdown\", \"value\":" (.LastAppliedConfigurationValue $resource "{.spec.shutdown}" "false") "}]" )'
    cmd: kubectl
    when: (.ClusterDefinitions (((.NewClusterDefinitionsIterationSpec).WithGroup "viya.sas.com").WithResource "casdeployments"))
    withClusterResources:
      group: viya.sas.com
      labelSelector: sas.com/deployment=sas-viya,sas.com/zero-scale-phase!=never
      namespace: $namespace
      resource: casdeployments
