apiVersion: orchestration.sas.com/v2beta15
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-opendistro-operator
    sas.com/component-version: 7.52.2-20250911.1757593776425
  creationTimestamp: null
  labels:
    participate.lifecycle.sas.com/start-all-execute-phase-0: "true"
  name: start-all-execute-opensearch
spec:
  args:
  - name: namespace
  steps:
  - args:
    - patch
    - --namespace
    - $namespace
    - opendistroclusters
    - $resource.Name
    - --type
    - json
    - --patch
    - '(print "[{\"op\":\"replace\", \"path\": \"/spec/shutdown\", \"value\":" (.LastAppliedConfigurationValue $resource "{.spec.shutdown}" "false") "}]" )'
    cmd: kubectl
    when: (.ClusterDefinitions (((.NewClusterDefinitionsIterationSpec).WithGroup "opendistro.sas.com").WithResource "opendistroclusters"))
    withClusterResources:
      group: opendistro.sas.com
      labelSelector: sas.com/deployment=sas-viya,sas.com/zero-scale-phase!=never
      namespace: $namespace
      resource: opendistroclusters
