apiVersion: orchestration.sas.com/v2beta15
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-opendistro-operator
    sas.com/component-version: 7.52.2-20250911.1757593776425
  creationTimestamp: null
  labels:
    participate.lifecycle.sas.com/stop-all-execute-phase-0: "true"
  name: stop-all-execute-opensearch
spec:
  args:
  - name: namespace
  - default: 7200s
    name: timeout
  steps:
  - args:
    - patch
    - --namespace
    - $namespace
    - opendistroclusters
    - $resource.Name
    - --type
    - json
    - --patch
    - '[{"op":"replace", "path": "/spec/shutdown", "value":true}]'
    cmd: kubectl
    when: (.ClusterDefinitions (((.NewClusterDefinitionsIterationSpec).WithGroup "opendistro.sas.com").WithResource "opendistroclusters"))
    withClusterResources:
      group: opendistro.sas.com
      labelSelector: sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
      namespace: $namespace
      resource: opendistroclusters
