apiVersion: orchestration.sas.com/v2beta15
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-crunchy5-postgres-operator
    sas.com/component-version: 1.6.3-20250609.1749489660207
  creationTimestamp: null
  labels:
    participate.lifecycle.sas.com/stop-all-execute-phase-0: "true"
  name: stop-all-execute-crunchy
spec:
  args:
  - name: namespace
  - default: 7200s
    name: timeout
  steps:
  - args:
    - patch
    - --namespace
    - $namespace
    - postgresclusters.postgres-operator.crunchydata.com
    - $resource.Name
    - --type
    - json
    - --patch
    - '[{"op":"replace", "path": "/spec/shutdown", "value":true}]'
    cmd: kubectl
    when: (.ClusterDefinitions (((.NewClusterDefinitionsIterationSpec).WithGroup "postgres-operator.crunchydata.com").WithResource "postgresclusters"))
    withClusterResources:
      group: postgres-operator.crunchydata.com
      labelSelector: sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
      namespace: $namespace
      resource: postgresclusters
      version: v1beta1
  - args:
    - wait
    - --namespace
    - $namespace
    - --for
    - delete
    - pod
    - --selector
    - postgres-operator.crunchydata.com/cluster,!job-name
    - --timeout
    - $timeout
    cmd: kubectl
