apiVersion: orchestration.sas.com/v2beta15
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-k8s-common
    sas.com/component-version: 2.108.0-20250904.1756998319075
  creationTimestamp: null
  name: stop-all-execute
spec:
  args:
  - name: namespace
  - default: 7200s
    name: timeout
  steps:
  - args:
    - scale
    - --namespace
    - $namespace
    - deployments
    - --replicas
    - "0"
    - --selector
    - sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
    cmd: kubectl
  - args:
    - scale
    - --namespace
    - $namespace
    - statefulsets
    - --replicas
    - "0"
    - --selector
    - sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
    cmd: kubectl
  - args:
    - patch
    - --namespace
    - $namespace
    - cronjobs
    - $resource.Name
    - --patch
    - '{"spec":{"suspend":true}}'
    cmd: kubectl
    withClusterResources:
      group: batch
      labelSelector: sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
      namespace: $namespace
      resource: cronjobs
  - args:
    - patch
    - --namespace
    - $namespace
    - cronjobs
    - $resource.Name
    - --patch
    - '{"spec":{"suspend":true}}'
    cmd: kubectl
    withClusterResources:
      group: batch
      labelSelector: sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
      namespace: $namespace
      resource: cronjobs
  - args:
    - patch
    - --namespace
    - $namespace
    - daemonsets
    - $resource.Name
    - --patch
    - '{"spec":{"template":{"spec":{"nodeSelector":{"sas.com/scale-class":"zero"}}}}}'
    cmd: kubectl
    withClusterResources:
      group: apps
      labelSelector: sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
      namespace: $namespace
      resource: daemonsets
  - always: true
    args:
    - $operation
    - --namespace
    - $namespace
    - --timeout
    - $timeout
    cmd: run
    withOperations:
      labelSelector: participate.lifecycle.sas.com/stop-all-execute-phase-0=true
  - args:
    - scale
    - --namespace
    - $namespace
    - deployments
    - --replicas
    - "0"
    - --selector
    - sas.com/deployment=sas-viya,sas.com/zero-scale-phase=1
    cmd: kubectl
