---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-config-reconciler
    sas.com/admin: namespace
  name: sas-config-reconciler
spec:
  routes:
  - conditions:
    - prefix: /configReconciler
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /configReconciler/
    services:
    - name: sas-config-reconciler
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /configReconciler/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-config-reconciler
      port: 80
    timeoutPolicy:
      response: 300s

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-configuration
    sas.com/admin: namespace
  name: sas-configuration
spec:
  routes:
  - conditions:
    - prefix: /configuration
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /configuration/
    services:
    - name: sas-configuration
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /configuration/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-configuration
      port: 80
    timeoutPolicy:
      response: 300s

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-feature-flags
    sas.com/admin: namespace
  name: sas-feature-flags
spec:
  routes:
  - conditions:
    - prefix: /featureFlags
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /featureFlags/
    services:
    - name: sas-feature-flags
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /featureFlags/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-feature-flags
      port: 80
    timeoutPolicy:
      response: 300s

