apiVersion: builtin
kind: PatchTransformer
metadata:
  name: buildkitd-certificates-transformer
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      mountPath: /etc/ssl/certs
      name: buildkit-registry-certs
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: buildkit-registry-certs
      secret:
        secretName: sas-buildkit-registry-secrets
target:
  name: buildkitd
  group: apps
  kind: Deployment
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: model-publish-buildkit-certificates-transformer
patch: |-
  - op: add
    path: /template/spec/containers/0/volumeMounts/-
    value:
      mountPath: /etc/ssl/certs
      name: buildkit-registry-certs
  - op: add
    path: /template/spec/volumes/-
    value:
      name: buildkit-registry-certs
      secret:
        secretName: sas-buildkit-registry-secrets
target:
  name: sas-model-publish-buildkit-job-config
  kind: PodTemplate
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: decisions-runtime-buildkit-certificates-transformer
patch: |-
  - op: add
    path: /template/spec/containers/0/volumeMounts/-
    value:
      mountPath: /etc/ssl/certs
      name: buildkit-registry-certs
  - op: add
    path: /template/spec/volumes/-
    value:
      name: buildkit-registry-certs
      secret:
        secretName: sas-buildkit-registry-secrets
target:
  name: sas-decisions-runtime-builder-buildkit-job-config
  kind: PodTemplate
  version: v1
