
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-catalog-services
  name: sas-catalog-services

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-providers: jobExecution-provider,jobExecution-provider-CATALOG
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-catalog-services
    sas.com/admin: namespace
    sas.com/registry-sync: default
  name: sas-catalog
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: sas-catalog-services
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-providers: jobExecution-provider,jobExecution-provider-CATALOG-TABLE-BOT
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-catalog-services
    sas.com/admin: namespace
    sas.com/registry-sync: default
  name: sas-catalog-table-bot
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: sas-catalog-services
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-catalog-services
    sas.com/admin: namespace
    sas.com/registry-sync: default
  name: sas-glossary
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: sas-catalog-services
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-catalog-services
    sas.com/admin: namespace
    sas.com/registry-sync: default
  name: sas-relationships
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: sas-catalog-services
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/elasticsearch-consumer: "true"
    sas.com/kustomize-base: golang
    sas.com/pod-uses-db-migrator: "true"
    sas.com/pod-uses-liveness-probe: http
    sas.com/pod-uses-readiness-probe: http
    sas.com/pod-uses-startup-probe: http
    sidecar.istio.io/proxyCPU: 15m
    sidecar.istio.io/proxyMemory: 115Mi
  labels:
    app.kubernetes.io/name: sas-catalog-services
    sas.com/admin: namespace
    sas.com/deployment-base: golang
    workload.sas.com/class: stateless
  name: sas-catalog-services
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-catalog-services
  template:
    metadata:
      annotations:
        prometheus.io/path: /internal/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        sas.com/certificate-file-format: pem
        sas.com/kustomize-base: golang
        sas.com/pod-uses-liveness-probe: http
        sas.com/pod-uses-readiness-probe: http
        sas.com/pod-uses-startup-probe: http
        sidecar.istio.io/proxyCPU: 15m
        sidecar.istio.io/proxyMemory: 115Mi
      labels:
        app: sas-catalog-services
        app.kubernetes.io/name: sas-catalog-services
        workload.sas.com/class: stateless
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - sas-catalog-services
              topologyKey: kubernetes.io/hostname
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution: []
      automountServiceAccountToken: true
      containers:
      - env:
        - name: SAS_K8S_DEPLOYMENT_NAME
          value: sas-catalog-services
        envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - secretRef:
            name: sas-consul-client
        - configMapRef:
            name: sas-catalog-database-config
        - configMapRef:
            name: sas-catalog-security-config
        - configMapRef:
            name: sas-catalog-services-config
        image: sas-catalog-services
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/live
            port: http
            scheme: HTTP
          periodSeconds: 20
          timeoutSeconds: 5
        name: sas-catalog-services
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/ready
            port: http
            scheme: HTTP
          periodSeconds: 20
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 180
          httpGet:
            path: /internal/live
            port: http
            scheme: HTTP
          periodSeconds: 10
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      imagePullSecrets: []
      initContainers:
      - args:
        - cp -rf meta /data
        command:
        - /bin/sh
        - -c
        image: sas-catalog-services
        imagePullPolicy: IfNotPresent
        name: hydrator
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 75m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: shared-vol
      - env:
        - name: SAS_SERVICE_NAME
          value: sas-catalog-services
        - name: SAS_MULTI_TENANCY_REGISTER_SERVICE
          value: "false"
        envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - configMapRef:
            name: sas-java-config
        - secretRef:
            name: sas-consul-client
        image: sas-db-migrator
        imagePullPolicy: IfNotPresent
        name: sas-db-migrator
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 90Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: shared-vol
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: sas-catalog-services
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless
      volumes:
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: shared-vol

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    sas.com/ha-class: centralized
    sas.com/kustomize-base: base
  name: sas-catalog-services
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-catalog-services

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    sas.com/ha-class: centralized
    sas.com/kustomize-base: golang
  name: sas-catalog-services
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sas-catalog-services

---
apiVersion: v1
kind: PodTemplate
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/elasticsearch-consumer: "true"
    sas.com/kustomize-base: base
  labels:
    sas.com/admin: namespace
    sas.com/template-intent: sas-launcher
  name: sas-catalog-job
template:
  metadata:
    annotations:
      sas.com/certificate-file-format: pem
      sas.com/kustomize-base: base
    labels: {}
  spec:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: In
              values:
              - stateless
          weight: 100
        - preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: NotIn
              values:
              - cas
              - compute
              - stateful
          weight: 50
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.azure.com/mode
              operator: NotIn
              values:
              - system
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []
        requiredDuringSchedulingIgnoredDuringExecution: []
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []
        requiredDuringSchedulingIgnoredDuringExecution: []
    automountServiceAccountToken: false
    containers:
    - env:
      - name: SAS_ELASTICSEARCH_USERNAME
        valueFrom:
          secretKeyRef:
            key: username
            name: sas-opendistro-sasadmin-secret
      - name: SAS_ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: sas-opendistro-sasadmin-secret
      envFrom:
      - configMapRef:
          name: sas-go-config
      - configMapRef:
          name: sas-shared-config
      - secretRef:
          name: sas-consul-client
      - configMapRef:
          name: sas-opendistro-client-config
      - configMapRef:
          name: sas-catalog-database-config
      - configMapRef:
          name: sas-catalog-security-config
      - configMapRef:
          name: sas-catalog-services-config
      - configMapRef:
          name: sas-catalog-job-config
      image: sas-catalog-services
      name: sas-catalog-job
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
      volumeMounts:
      - mountPath: /tmp
        name: tmp
    imagePullSecrets: []
    initContainers: []
    restartPolicy: Never
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    tolerations:
    - effect: NoSchedule
      key: workload.sas.com/class
      operator: Equal
      value: stateless
    - effect: NoSchedule
      key: workload.sas.com/class
      operator: Equal
      value: stateful
    volumes:
    - emptyDir: {}
      name: tmp
