
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-compute
  name: sas-compute

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-providers: jobExecution-provider-Compute,dataSources-provider-Compute,dataTables-provider-Compute,rowSets-provider-Compute,jobExecution-provider,dataSources-provider,dataTables-provider,rowSets-provider
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-compute
    sas.com/admin: namespace
    sas.com/registry-sync: default
  name: sas-compute
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: sas-compute
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/kustomize-base: golang
    sas.com/pod-uses-db-migrator: "true"
    sas.com/pod-uses-liveness-probe: http
    sas.com/pod-uses-readiness-probe: http
    sas.com/pod-uses-startup-probe: http
    sidecar.istio.io/proxyCPU: 15m
    sidecar.istio.io/proxyMemory: 115Mi
  labels:
    app.kubernetes.io/name: sas-compute
    sas.com/admin: namespace
    sas.com/deployment-base: golang
    workload.sas.com/class: stateless
  name: sas-compute
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-compute
  template:
    metadata:
      annotations:
        prometheus.io/path: /internal/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        sas.com/certificate-file-format: pem
        sas.com/kustomize-base: golang
        sas.com/pod-uses-liveness-probe: http
        sas.com/pod-uses-readiness-probe: http
        sas.com/pod-uses-startup-probe: http
        sidecar.istio.io/proxyCPU: 15m
        sidecar.istio.io/proxyMemory: 115Mi
      labels:
        app: sas-compute
        app.kubernetes.io/name: sas-compute
        workload.sas.com/class: stateless
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - sas-compute
              topologyKey: kubernetes.io/hostname
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution: []
      automountServiceAccountToken: true
      containers:
      - env:
        - name: SAS_K8S_DEPLOYMENT_NAME
          value: sas-compute
        envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - secretRef:
            name: sas-consul-client
        - configMapRef:
            name: sas-compute-config
        image: sas-compute
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/live
            port: http
            scheme: HTTP
          periodSeconds: 20
          timeoutSeconds: 5
        name: sas-compute
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/ready
            port: http
            scheme: HTTP
          periodSeconds: 20
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 180
          httpGet:
            path: /internal/live
            port: http
            scheme: HTTP
          periodSeconds: 10
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      imagePullSecrets: []
      initContainers:
      - args:
        - cp -rf meta /data
        command:
        - /bin/sh
        - -c
        image: sas-compute
        imagePullPolicy: IfNotPresent
        name: hydrator
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 75m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: shared-vol
      - env:
        - name: SAS_SERVICE_NAME
          value: sas-compute
        - name: SAS_MULTI_TENANCY_REGISTER_SERVICE
          value: "false"
        envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - configMapRef:
            name: sas-java-config
        - secretRef:
            name: sas-consul-client
        image: sas-db-migrator
        imagePullPolicy: IfNotPresent
        name: sas-db-migrator
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 90Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: shared-vol
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: sas-compute
      terminationGracePeriodSeconds: 60
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless
      volumes:
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: shared-vol

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    sas.com/ha-class: centralized
    sas.com/kustomize-base: base
  name: sas-compute
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-compute

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    sas.com/ha-class: decentralized
    sas.com/kustomize-base: decentralized
  name: sas-compute-job
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      launcher.sas.com/job-type: compute-server

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    sas.com/ha-class: centralized
    sas.com/kustomize-base: golang
  name: sas-compute
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sas-compute

---
apiVersion: v1
kind: PodTemplate
metadata:
  annotations:
    launcher.sas.com/jobContainerName: sas-programming-environment
    sas.com/certificate-file-format: pem
    sas.com/config-init-mode: initcontainer
    sas.com/kustomize-base: sas-programming-environment
    sas.com/sas-access-config: "true"
    sas.com/sas-kerberos-config: "true"
    sas.com/sas-sssd-config: "true"
    sas.com/tenant-resource: "true"
  labels:
    sas.com/admin: namespace
    sas.com/pod-container-image: sas-programming-environment
    sas.com/template-intent: sas-launcher
    workload.sas.com/class: compute
  name: sas-compute-job-config
template:
  metadata:
    annotations:
      sas.com/certificate-file-format: pem
      sas.com/kustomize-base: sas-programming-environment
      sidecar.istio.io/inject: "false"
    labels:
      launcher.sas.com/job-type: compute-server
  spec:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: In
              values:
              - compute
          weight: 100
        - preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: NotIn
              values:
              - cas
              - stateless
              - stateful
          weight: 50
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.azure.com/mode
              operator: NotIn
              values:
              - system
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []
        requiredDuringSchedulingIgnoredDuringExecution: []
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []
        requiredDuringSchedulingIgnoredDuringExecution: []
    automountServiceAccountToken: true
    containers:
    - env:
      - name: SAS_K8S_POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: SAS_K8S_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: SAS_LICENSE
        valueFrom:
          secretKeyRef:
            key: SAS_LICENSE
            name: sas-license
      - name: SASCLOUDNATIVE
        value: "1"
      - name: LAUNCH_AS_JOB
        value: "true"
      - name: COMPUTESERVER_USER_CONFIG
        value: /config
      - name: COMPUTESERVER_VAR_PATH
        value: /opt/sas/viya/config/var
      envFrom:
      - configMapRef:
          name: sas-access-config
      - configMapRef:
          name: sas-deployment-metadata
      - configMapRef:
          name: sas-launcher-lockdown-config
      - configMapRef:
          name: sas-programming-environment-path-config
      - configMapRef:
          name: sas-shared-config
      - configMapRef:
          name: sas-compute-server-config
      image: sas-programming-environment
      name: sas-programming-environment
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
      volumeMounts:
      - mountPath: /tmp
        name: tmp
      - mountPath: /sasuser
        name: sasuser
      - mountPath: /sashelp
        name: sashelp
      - mountPath: /config
        name: config
      - mountPath: /opt/sas/viya/config/var
        name: viya
      - mountPath: /opt/sas/viya/home/commonfiles
        name: commonfilesvols
        readOnly: true
    imagePullSecrets: []
    initContainers:
    - env:
      - name: SAS_K8S_POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: SAS_K8S_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      envFrom:
      - configMapRef:
          name: sas-go-config
      - configMapRef:
          name: sas-shared-config
      - secretRef:
          name: sas-consul-client
      - configMapRef:
          name: sas-programming-environment-path-config
      - configMapRef:
          name: sas-deployment-metadata
      - configMapRef:
          name: sas-programming-environment-java-policy-config
      - configMapRef:
          name: sas-access-config
      - configMapRef:
          name: sas-compute-server-config
      image: sas-config-init
      name: sas-config-init
      resources:
        limits:
          cpu: 2
          memory: 500Mi
        requests:
          cpu: 50m
          memory: 50Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 1001
        runAsUser: 1001
      volumeMounts:
      - mountPath: /tmp
        name: config-init-tmp
      - mountPath: /config
        name: config
      - mountPath: /opt/sas/viya/config/var
        name: viya
      - mountPath: /opt/sas/viya/home/commonfiles
        name: commonfilesvols
        readOnly: true
    restartPolicy: Never
    securityContext:
      fsGroupChangePolicy: OnRootMismatch
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    serviceAccountName: sas-programming-environment
    tolerations:
    - effect: NoSchedule
      key: workload.sas.com/class
      operator: Equal
      value: compute
    volumes:
    - emptyDir: {}
      name: tmp
    - emptyDir: {}
      name: config-init-tmp
    - emptyDir: {}
      name: sasuser
    - emptyDir: {}
      name: sashelp
    - emptyDir: {}
      name: config
    - emptyDir: {}
      name: viya
    - name: commonfilesvols
      persistentVolumeClaim:
        claimName: sas-commonfiles
        readOnly: true
