
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/component-name: sas-restore-job
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-restore-job
    sas.com/admin: namespace
    sas.com/backup-job-type: restore
    workload.sas.com/class: stateless
  name: sas-restore-job
spec:
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: sas-restore-job
        sas.com/admin: namespace
        sas.com/backup-job-type: restore
    spec:
      template:
        metadata:
          annotations:
            sas.com/certificate-file-format: pem
            sas.com/kustomize-base: base
          labels:
            app.kubernetes.io/name: sas-restore-job
            sas.com/admin: namespace
            sas.com/backup-job-type: restore
            workload.sas.com/class: stateless
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: workload.sas.com/class
                    operator: In
                    values:
                    - stateless
                weight: 100
              - preference:
                  matchExpressions:
                  - key: workload.sas.com/class
                    operator: NotIn
                    values:
                    - cas
                    - compute
                    - stateful
                weight: 50
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.azure.com/mode
                    operator: NotIn
                    values:
                    - system
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution: []
              requiredDuringSchedulingIgnoredDuringExecution: []
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution: []
              requiredDuringSchedulingIgnoredDuringExecution: []
          automountServiceAccountToken: true
          containers:
          - env:
            - name: BACKUP_MOUNT_LOCATION
              value: /sasviyabackup
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JOB_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['job-name']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RESTORE_RETENTION_PERIOD
              valueFrom:
                configMapKeyRef:
                  key: RETENTION_PERIOD
                  name: sas-backup-job-parameters
                  optional: true
            envFrom:
            - configMapRef:
                name: sas-go-config
            - configMapRef:
                name: sas-shared-config
            - configMapRef:
                name: sas-java-config
            - configMapRef:
                name: sas-restore-job-parameters
            - secretRef:
                name: sas-consul-client
            image: sas-restore-job
            name: sas-restore-job
            resources:
              limits:
                cpu: "2"
                memory: 4Gi
              requests:
                cpu: 50m
                memory: 50Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add: []
                drop:
                - ALL
              privileged: false
              readOnlyRootFilesystem: true
            volumeMounts:
            - mountPath: /sasviyabackup
              name: backup
            - mountPath: /sasviyabackuplog
              name: backup
            - mountPath: /tmp
              name: tmp
          imagePullSecrets: []
          initContainers: []
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            supplementalGroups: []
            sysctls: []
          serviceAccountName: sas-viya-backuprunner
          tolerations:
          - effect: NoSchedule
            key: workload.sas.com/class
            operator: Equal
            value: stateless
          - effect: NoSchedule
            key: workload.sas.com/class
            operator: Equal
            value: stateful
          volumes:
          - emptyDir: {}
            name: tmp
          - name: backup
            persistentVolumeClaim:
              claimName: sas-common-backup-data
      ttlSecondsAfterFinished: 2592000
  schedule: '* * 30 2 *'
  successfulJobsHistoryLimit: 100
  suspend: true

---
apiVersion: v1
kind: PodTemplate
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-restore-job
    sas.com/admin: namespace
    sas.com/backup-job-type: restore
    sas.com/restore-pod-type: pv-restore
    workload.sas.com/class: stateless
  name: sas-pv-restore
template:
  metadata:
    annotations:
      sas.com/certificate-file-format: pem
      sas.com/kustomize-base: base
    labels:
      workload.sas.com/class: stateless
  spec:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: In
              values:
              - stateless
          weight: 100
        - preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: NotIn
              values:
              - cas
              - compute
              - stateful
          weight: 50
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.azure.com/mode
              operator: NotIn
              values:
              - system
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []
        requiredDuringSchedulingIgnoredDuringExecution: []
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []
        requiredDuringSchedulingIgnoredDuringExecution: []
    automountServiceAccountToken: true
    containers:
    - args:
      - -c
      - |
        /opt/sas/viya/home/bin/restore_pv.sh
      command:
      - /bin/bash
      env:
      - name: BACKUP_MOUNT_LOCATION
        value: /sasviyabackup
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      envFrom:
      - configMapRef:
          name: sas-go-config
      - configMapRef:
          name: sas-shared-config
      - configMapRef:
          name: sas-java-config
      - configMapRef:
          name: sas-backup-agent-parameters
      - secretRef:
          name: sas-consul-client
      - configMapRef:
          name: sas-restore-job-parameters
      image: sas-restore-job
      lifecycle:
        preStop:
          exec:
            command:
            - bash
            - -c
            - |
              kill -SIGKILL $(ps -Af | grep 'restore_pv.sh' | grep -v grep | awk '{print $2}')
      name: sas-pv-restore
      resources:
        limits:
          cpu: "1"
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 50Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
      volumeMounts:
      - mountPath: /sasviyabackup
        name: backup
      - mountPath: /tmp
        name: tmp
    imagePullSecrets: []
    initContainers: []
    restartPolicy: Never
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      supplementalGroups: []
      sysctls: []
    serviceAccountName: sas-viya-backuprunner
    shareProcessNamespace: true
    tolerations:
    - effect: NoSchedule
      key: workload.sas.com/class
      operator: Equal
      value: stateless
    - effect: NoSchedule
      key: workload.sas.com/class
      operator: Equal
      value: stateful
    volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: sas-common-backup-data
    - emptyDir: {}
      name: tmp
